spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

server:
  port: 9090

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url: 
            defaultZone: http://localhost:8761/eureka